development:
  adapter: postgresql
  encoding: unicode
  database: angular_dev
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: angular_test
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: angular_prod
  host: localhost
  username: postgres
  password: postgres
